export const copy = {
  landing: {
    eyebrow: "GDG ON CAMPUS BABCOCK",
    title: "WRAPPED",
    year: "2025–26",
    sub: "The year the chapter shipped, showed up, and showed off. Now it's your turn to see where you fit in it.",
    ctaWatch: "Watch the year",
    ctaPersonal: "Get your Wrapped",
    emailLabel: "Your email",
    emailPlaceholder: "you@school.edu",
    emailSubmit: "Send my link",
    emailSent: "Check your inbox. Your Wrapped is waiting.",
    emailHint: "We'll email you a magic link. No password, no signup.",
  },
  theYear: {
    setup: "What a year.",
    setupSub: "No, really. Look at the receipts.",
    // The cold open (§11.4 build2.md): a hard-cut three-line title sequence
    // in place of the single setup line above (setup/setupSub stay defined
    // for anywhere else that might reference them, e.g. the chapter grid
    // teaser copy, but the on-screen setup beat now renders coldOpen).
    coldOpen: [
      { line: "One chapter.", field: "ink" as const },
      { line: "One unhinged year.", field: "cream" as const },
      { line: "What a year.", field: "ink" as const },
      { line: "We kept the receipts.", field: "cream" as const, accentWord: "receipts" },
    ],
    revealLabel: "GDG BABCOCK · 2025/26",
    rows: [
      { label: "EVENTS RUN", key: "eventsRun" },
      { label: "MEMBERS", key: "members" },
      { label: "PRODUCTS SHIPPED", key: "productsShipped" },
      { label: "CHECK-INS LOGGED", key: "totalCheckins" },
      { label: "MESSAGES SENT", key: "messagesParsed" },
    ],
    footer: "ONE CHAPTER. ONE YEAR. KEEP THE RECEIPT.",
  },
  moments: {
    setup: "Some nights you just had to be there.",
    reveal: "The moments that made the year.",
  },
  built: {
    setup: "Talk is cheap.",
    setupSub: "We ship.",
    revealLabel: "SHIPPED 2025/26",
    footer: "ALL LIVE. ALL OURS.",
  },
  people: {
    setup: "None of this happened by itself.",
    reveal: "Roll credits.",
  },
  yourEvents: {
    setup: "You didn't just watch from the sidelines.",
    reveal: "You checked into {checkins} events this year.",
    revealOne: "You checked into 1 event this year. It counted.",
    sub: "Out of {registrations} you signed up for. We noticed.",
    subPerfect: "Every single one you signed up for. Flawless.",
    zeroSetup: "The room was always open.",
    zeroReveal: "{eventsRun} events happened this year.",
    zeroSub: "Next year, one of those seats has your name on it. Literally — we do check-ins.",
    guestSetup: "This part's members-only.",
    guestReveal: "Not a flex — an invitation.",
    guestSub: "Join GDG Babcock and next year this screen is about you.",
  },
  standing: {
    setup: "You showed up. Loudly.",
    setupQuiet: "We did the math on you.",
    revealTier: "TOP {percentile}%",
    revealTierSub: "of the GDG Babcock community this year, by activity.",
    sealText: "GDG BABCOCK · CERTIFIED · 25/26",
    revealStats: "You made yourself known.",
    statMessages: "MESSAGES SENT",
    statEvents: "EVENTS CHECKED IN",
    revealStatsSub: "Part of the signal, not the noise.",
    lowSub: "Quietly present. That still counts for something here.",
  },
  yourChapter: {
    setup: "You've been here longer than you think.",
    setupNew: "Some people wait years to find their people.",
    reveal: "Here since {joinMonthLabel}.",
    revealNew: "You found us in {joinMonthLabel}.",
    tenure: "{tenureMonths} months of showing up.",
    tenureUnderOne: "And you're just getting started.",
    loreBefore: "That's before {milestone} was even an idea.",
    loreNew: "Late to the year, right on time for what's next.",
  },
  yourClub: {
    setup: "Everyone plays this their own way.",
    setupSub: "We sorted the whole chapter into four clubs. Here's yours.",
    revealPrefix: "YOU'RE A",
    rarity: "{rarityPct}% OF THE CHAPTER",
    guestNames: "BUILDER · CONNECTOR · OBSERVER · SPRINTER",
    guestLine: "Four clubs. Every member belongs to one. Which one are you? Join and find out next year.",
  },
  whatsNext: {
    setup: "This isn't an ending.",
    revealTitle: "THE 100 IS LIVE.",
    revealSub: "100 students shaping Babcock, documented for good — built by this chapter. And a new leadership era starts now.",
    ctaHundred: "See The 100",
    ctaJoin: "Join GDG Babcock",
  },
  summary: {
    title: "WRAPPED 25/26",
    memberSince: "MEMBER SINCE",
    club: "CLUB",
    standing: "STANDING",
    standingValue: "TOP {percentile}%",
    standingValueMember: "PRESENT & COUNTED",
    statEvents: "EVENTS",
    statMessages: "MESSAGES",
    statMonths: "MONTHS IN",
    share: "Share your card",
    download: "Save image",
    replay: "Watch again",
    guestTitle: "THE YEAR GDG BABCOCK SHIPPED",
    guestSub: "Be on this card next year.",
    guestCta: "Join the chapter",
  },
  grid: {
    "the-year": "The receipts.",
    moments: "You had to be there.",
    built: "Five products. All live.",
    people: "Roll credits.",
    "your-events": "Your attendance record.",
    standing: "Where you rank.",
    "your-chapter": "Your era.",
    "your-club": "Which club are you?",
    "whats-next": "The 100 is live.",
    summary: "Your card.",
  },
  email: {
    subject: "Your GDG Wrapped is ready",
    heading: "Your year, wrapped.",
    body: "Tap the button to unlock your personal GDG Babcock Wrapped — your events, your standing, your club.",
    button: "Open my Wrapped",
    expiry: "This link works for 15 minutes. If it expires, just request a new one.",
    ignore: "If you didn't request this, you can safely ignore this email.",
  },
  errors: {
    linkExpired: "That link has expired. Request a fresh one — it takes ten seconds.",
    generic: "Something hiccuped. Try again.",
    dbDown: "Your personal stories are having a moment. The chapter's year still plays — try yours again in a bit.",
  },
} as const;

export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}
