import type { Snapshot } from "@/lib/snapshot";

const base = {
  version: 1 as const,
  events: {
    titles: ["DevFest Babcock", "Game Night Vol. 3", "ORBIT Kickoff"],
    firstEventTitle: "ORBIT Kickoff",
  },
};

export const FIXTURES: Record<string, Snapshot> = {
  top1: {
    ...base,
    name: "Ada Lovelace",
    firstName: "Ada",
    joinDate: "2024-09-15",
    joinMonthLabel: "September 2024",
    tenureMonths: 22,
    isNewMember: false,
    events: { checkins: 34, registrations: 36, ...base.events },
    messages: { matched: true, count: 2100, activeDays: 210, peakMonthLabel: "November" },
    standing: { percentile: 1, tier: "top1" },
    club: { id: "sprinter", rarityPct: 11 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  member: {
    ...base,
    name: "Grace Hopper",
    firstName: "Grace",
    joinDate: "2025-02-10",
    joinMonthLabel: "February 2025",
    tenureMonths: 17,
    isNewMember: false,
    events: { checkins: 5, registrations: 6, ...base.events },
    messages: { matched: true, count: 180, activeDays: 40, peakMonthLabel: "March" },
    standing: { percentile: 55, tier: "member" },
    club: { id: "builder", rarityPct: 28 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  zero: {
    ...base,
    name: "Zero Zealous",
    firstName: "Zero",
    joinDate: "2026-04-01",
    joinMonthLabel: "April 2026",
    tenureMonths: 3,
    isNewMember: true,
    events: { checkins: 0, registrations: 0, titles: [], firstEventTitle: null },
    messages: { matched: false },
    standing: { percentile: 80, tier: "member" },
    club: { id: "observer", rarityPct: 25 },
    flags: { zeroCheckins: true, lowActivity: true },
  },
  newmember: {
    ...base,
    name: "Nia New",
    firstName: "Nia",
    joinDate: "2026-05-20",
    joinMonthLabel: "May 2026",
    tenureMonths: 2,
    isNewMember: true,
    events: { checkins: 2, registrations: 2, titles: ["The 100 Launch"], firstEventTitle: "The 100 Launch" },
    messages: { matched: true, count: 60, activeDays: 15, peakMonthLabel: "June" },
    standing: { percentile: 40, tier: "member" },
    club: { id: "connector", rarityPct: 24 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  unmatched: {
    ...base,
    name: "Uche Unmatched",
    firstName: "Uche",
    joinDate: "2025-09-01",
    joinMonthLabel: "September 2025",
    tenureMonths: 11,
    isNewMember: false,
    events: { checkins: 9, registrations: 10, ...base.events },
    messages: { matched: false },
    standing: { percentile: 15, tier: "top25" },
    club: { id: "builder", rarityPct: 28 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  builder: {
    ...base,
    name: "Beth Builder",
    firstName: "Beth",
    joinDate: "2024-10-01",
    joinMonthLabel: "October 2024",
    tenureMonths: 21,
    isNewMember: false,
    events: { checkins: 20, registrations: 22, ...base.events },
    messages: { matched: true, count: 300, activeDays: 90, peakMonthLabel: "January" },
    standing: { percentile: 8, tier: "top10" },
    club: { id: "builder", rarityPct: 28 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  connector: {
    ...base,
    name: "Cara Connector",
    firstName: "Cara",
    joinDate: "2025-01-15",
    joinMonthLabel: "January 2025",
    tenureMonths: 18,
    isNewMember: false,
    events: { checkins: 8, registrations: 9, ...base.events },
    messages: { matched: true, count: 1400, activeDays: 200, peakMonthLabel: "October" },
    standing: { percentile: 3, tier: "top5" },
    club: { id: "connector", rarityPct: 24 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  observer: {
    ...base,
    name: "Owen Observer",
    firstName: "Owen",
    joinDate: "2024-11-20",
    joinMonthLabel: "November 2024",
    tenureMonths: 20,
    isNewMember: false,
    events: { checkins: 3, registrations: 12, ...base.events },
    messages: { matched: true, count: 40, activeDays: 30, peakMonthLabel: "December" },
    standing: { percentile: 60, tier: "member" },
    club: { id: "observer", rarityPct: 25 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
  sprinter: {
    ...base,
    name: "Sam Sprinter",
    firstName: "Sam",
    joinDate: "2026-02-01",
    joinMonthLabel: "February 2026",
    tenureMonths: 6,
    isNewMember: false,
    events: { checkins: 12, registrations: 12, ...base.events },
    messages: { matched: true, count: 900, activeDays: 25, peakMonthLabel: "March" },
    standing: { percentile: 5, tier: "top5" },
    club: { id: "sprinter", rarityPct: 11 },
    flags: { zeroCheckins: false, lowActivity: false },
  },
};

export type FixtureName = keyof typeof FIXTURES;
